name: coverage

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  coverage-cloudLib:
    name: coverage-cloudLib
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: set up jdk
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" | base64 -d > cloudLib/local.properties

      - name: gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: cloudlib
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          script: ./gradlew :cloudlib:testGoogleplayDebugCoverage

      - name: publish
        run: |
          set -x
          ls -al cloudlib/build/reports/*.xml
          bash <(curl https://codecov.io/bash) -t ${{ secrets.CODECOVIO_TOKEN }} -f cloudLib/build/reports/GoogleplayDebug.xml
