name: deploy-gcp

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  deploy-gcp:
    name: deploy-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: "10.22.1"

      - name: install npm dependencies
        run: |
          npm install -g express mocha chai chai-http nyc md5 @google-cloud/firestore markdownlint-cli jsonlint
          cd cloudLib/gcp
          ./npm-update.sh

      - name: static analysis
        run: |
          cd cloudLib/gcp
          markdownlint '**/*.md' --ignore functions/node_modules
